const WEATHER_API_KEY = 'YOUR_KEY_HERE';
const SERVER_URL = 'http://localhost:3000';
const GOOGLE_API_KEY = '1234';
const OPEN_WEATHER_API_KEY = '91aef6be37b3b1e6a9f283fa771c3dbb';
export { OPEN_WEATHER_API_KEY, SERVER_URL, GOOGLE_API_KEY, WEATHER_API_KEY };
